version: '3.9'

services:
  database:
    image: postgres
    container_name: database_base_clinica
    ports:
      - 5442:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app_network

  backend:
    build: 
      context: ./backend
    container_name: backend_base_clinica
    environment:
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_NAME=${POSTGRES_DB}
      - DATABASE_USER=${POSTGRES_USER}
      - DATABASE_PASSWORD=${POSTGRES_PASSWORD}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - MERCADO_PAGO_ACCESS_TOKEN=${MERCADO_PAGO_ACCESS_TOKEN}
    ports:
      - 3001:3001
    depends_on:
      - database
    restart: always
    networks:
      - app_network

  frontend:
    build: 
     context: ./frontend
    container_name: frontend_base_clinica
    environment:
      - REACT_APP_SYNCFUSION_LICENSE_KEY=${REACT_APP_SYNCFUSION_LICENSE_KEY}
      - REACT_APP_MERCADO_PAGO_PUBLIC_KEY=${REACT_APP_MERCADO_PAGO_PUBLIC_KEY}
    ports:
      - 8080:3000
    depends_on:
      - backend
    networks:
      - app_network

networks:
  app_network: